### ISSUE TITLE
Problem upgrading database to version 3 – missing tables/columns Iphone i WIndows desktop app

### ISSUE THREAD

**Issue by Mrgeniusxxxx** [moneymanagerex/moneymanagerex#7493]
Hi everyone,

I want to use the Money Manager EX app on both Windows desktop and iOS device via Dropbox synchronization.

However, I’m having trouble upgrading my existing database to version 3. When opening the database in the latest MMEX version on Windows, I get the following error:

SQL logic error[1]: no such table: BILLSDEPOSITS_V1
After manually adding that table, a new error appears:
SQL logic error[1]: no such column: NEXTOCCURRENCEDATE

I tried adding the missing tables and columns using SQLite, but it seems there are other structural inconsistencies preventing a successful upgrade.

Could someone help me with:

The correct database structure compatible with MMEX version 3?

Or suggest a proper way to migrate my old database so it works on both Windows and iOS?

Thanks in advance for the help!

**Comment by Mrgeniusxxxx** [comment]
Also, when I open my Windows-working database on iOS, the app crashes immediately.

**Comment by renato-mmex** [comment]
It would be helpful if you could tell us which MMEX versions you are using.

**Comment by Mrgeniusxxxx** [comment]
Desktop 1,9.0 64 ios 0.1.29

**Comment by georgeef** [comment]
The iOS app is still "work in progress".

**Comment by guanlisheng** [comment]
The key question might be how to upgrade to v1.9.0 from an old version (do you have version here?).  

> I’m having trouble upgrading my existing database to version 3. When opening the database in the latest MMEX version on Windows, I get the following error:
SQL logic error[1]: no such table: BILLSDEPOSITS_V1
After manually adding that table, a new error appears:
SQL logic error[1]: no such column: NEXTOCCURRENCEDATE


If you can share the old database file, we can take a look and upgrade it manually.  everything would be fine after upgrade.

**Comment by Mrgeniusxxxx** [comment]
https://we.tl/t-6PlxOt0Jz1

**Comment by guanlisheng** [comment]
Hey @Mrgeniusxxxx, here you go, the upgraded database file (please remove the `.txt` after download).

[x1b.mmb.txt](https://github.com/user-attachments/files/20267837/x1b.mmb.txt)

**Comment by Mrgeniusxxxx** [comment]
The sample database file I downloaded works fine in MMEX version 1.9 on Windows, but when I try to open it on my iPhone, the app crashes immediately — and after that, I can’t open the app at all until I reinstall it.

**Comment by Mrgeniusxxxx** [comment]
The sample database file I downloaded works fine in MMEX version 1.9 on Windows, but when I try to open it on my iPhone, the app crashes immediately — and after that, I can’t open the app at all until I reinstall it.

**Comment by guanlisheng** [comment]
ok, 
A quick response of iOS MMEX is that 

> SQLite/Query.swift:1235: Fatal error: 'try!' expression unexpectedly raised an error: Unexpected null value for column `"CURRENCY_SYMBOL"`

Seems mmex4ios has some room for its robustness. As a workaround, can you update the CURRENCY_SYMBOL to verify whether it works

**Comment by guanlisheng** [comment]
With the following quick fix, it works well on iOS now. 
```update CURRENCYFORMATS_V1 set CURRENCY_SYMBOL = PFX_SYMBOL where CURRENCY_SYMBOL is null;```


[x1b_valid_symbol.mmb.txt](https://github.com/user-attachments/files/20276694/x1b_valid_symbol.mmb.txt)

So far, both the schema and the iOS code expect this field to have a valid value
`, CURRENCY_SYMBOL TEXT COLLATE NOCASE NOT NULL UNIQUE`

` static let col_symbol         = SQLite.Expression<String>("CURRENCY_SYMBOL")`


@georgeef , do you have any idea?
