### ISSUE TITLE
Can't seem to install on Mint 18.3 Sylvia

### ISSUE THREAD

**Issue by Ericjar** [moneymanagerex/moneymanagerex#1409]
Running Linux Mint 18.3 have been using MMEX for a while on Windows and had another ubuntu system it was on but now I have downloaded mmex_1.1.0_1386.deb and when I try to run it as an install it starts to but then gives me an error "Dependency is not satisfiable: libwxbase3.0.0-unnoficial"

I am running 64 bit Mint so maybe I need another version of MMEX? I could not find it in the usual Software Manager so if that is the problem can someone direct me to where I can find the new version and how to install?

Thanks

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [x] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
MMEX 1.1.0 is ancient version and souln't be used.
I've succesfully build latest test MMEX version (1.4.x) for Mint 18.1 Serena using [build](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux) instructions.
I'll try to verify compilation on Mint 18.3.

**Comment by slodki** [comment]
There could be same problem as in #1331 in Mint 19 Tara - it will use Ubuntu 18.04 as a codebase.

**Comment by Ericjar** [comment]
Sounds great, let me know. I have used a lot of software (and wrote some for Windows and MS-DOS way back) and am trying to move whatever I can to Linux. Currently using ver. 1.2.1 on Windows 7 (portable mode). Not sure where I downloaded 1.1.0 for Linux. Not yet real familiar with Linux but learning ... I looked at those build instructions and they are a little confusing. Thanks again :)

**Comment by slodki** [comment]
We have packages for Mint 18.1 & 18.2 prepared - they will be ready to download with next 1.4.0-alpha.4 [MMEX release](https://github.com/moneymanagerex/moneymanagerex/releases).

For Mint 18.3 we must wait for [Docker OS image](https://hub.docker.com/r/vcatechnology/linux-mint/tags/) to be ready to test build process. You could build package yourself using [instructions](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md) if you have this OS version installed somewhere already.

**Comment by avma** [comment]
Hi,

Any news on a working version running on Mint 18.3?

Many thanks

**Comment by avma** [comment]
Hi, 

I am trying for a while to build the package from 'master'  (Commit : 2ada4733 (2018-03-22))by myself but  **make package** cli always ends with:

`[100%] Linking CXX executable mmex
/usr/bin/ld: libMMEXLib.a(relocatepayeedialog.cpp.o): undefined reference to symbol '_ZThn760_NK10wxTextCtrl7HitTestERK7wxPointPl@@WXU_3.0'
//usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/mmex.dir/build.make:100: recipe for target 'src/mmex' failed
make[2]: *** [src/mmex] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/mmex.dir/all' failed
make[1]: *** [src/CMakeFiles/mmex.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

I would appreciate your help
My regards
Avi

**Comment by vomikan** [comment]
@avma could you try
```apt-get install libwxgtk3.0-dev```

**Comment by avma** [comment]
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
libwxgtk3.0-dev is already the newest version (3.0.2+dfsg-1.3ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by slodki** [comment]
It [builds](https://travis-ci.org/slodki/moneymanagerex/jobs/356825829#L917) on clean 18.2 without errors using instructions from [BUILD](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md).

You can try to install [today's build](https://github.com/slodki/moneymanagerex/releases/tag/test1) on 18.3 but there is no guarantee it will work on it - 18.3 can use newer library versions etc.

**Comment by avma** [comment]
Huuum,

Until a month a go i was still able to compile from master (MMEX was not working but did install), now it will not compile any more...  
This is what  was  doing for the last 3 months:

`git clone --recursive https://github.com/moneymanagerex/moneymanagerex.git

cd moneymanagerex

mkdir build

cd build

cmake -DCMAKE_BUILD_TYPE=Release ../

make package`

Up to cmake... all looks good:

` **MMEX configuration summary**
  
 Version        : 1.4.0~alpha3
 Commit         : 94f89135 (2018-03-23)
 Branch         : master
 Build tests    : OFF
 Host system    : Linux x86_64
 Target system  : Linux x86_64
 Build types    : Release
 Generator      : Unix Makefiles
 Install prefix : /usr/local
 
 **Versions**
  
 Linux 4.15.12-041512-generic
 LinuxMint 18.3 'sylvia'
 CMake 3.10.2
 GNU Make 4.1
 GNU 5.4.0
 wxWidgets 3.1.1
 curl 7.47.0
 gettext 0.19.7
 
 Configuring done
 Generating done
 Build files have been written to: /home/avi/moneymanagerex/build`

But after ruining  make package, it ends with this error:
`[100%] Linking CXX executable mmex
/usr/bin/ld: libMMEXLib.a(relocatepayeedialog.cpp.o): undefined reference to symbol '_ZThn760_NK10wxTextCtrl7HitTestERK7wxPointPl@@WXU_3.0'
//usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/mmex.dir/build.make:100: recipe for target 'src/mmex' failed
make[2]: *** [src/mmex] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/mmex.dir/all' failed
make[1]: *** [src/CMakeFiles/mmex.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by slodki** [comment]
Please test binary packages at https://github.com/slodki/moneymanagerex/releases/tag/test2

**Comment by avma** [comment]
Yup,  you've done it! was able to install it and load my database... well done!
(sorry for not responding sooner, was traveling out of the country)
