### ISSUE TITLE
Cannot compile on macOS with latest Xcode (16.3)

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/moneymanagerex#7437]
MMEX version:
 - [x] master

Operating System:
 - [X] macOS (arm64)

## Problem 1: cannot compile wxWidgets-3.2.7

wxWidgets-3.2.7 includes `fp.h` (floating-point header), which does not exist in the latest Xcode toolchain.

See also: https://github.com/wxWidgets/wxWidgets/issues/24590

Temporary fix: edit `src/png/pngpriv.h`, in line 536 change `fp.h` -> `math.h`.

After this fix wxWidgets-3.2.7 compiles without errors, but I don't know if there are other side-effects.

## Problem 2: cannot compile moneymanagerex (error in 3rd/wxsqlite3)

wxsqlite3 uses the flag `-maes` (AES encryption), which is invalid for arm64 (it is x86_64 specific).

> clang: error: unsupported option '-maes' for target 'arm64-apple-darwin24.4.0'
> gmake[2]: *** [3rd/CMakeFiles/SQLite3.dir/build.make:79: 3rd/CMakeFiles/SQLite3.dir/wxsqlite3/src/sqlite3mc_amalgamation.c.o] Error 1

It seems that this flag was ignored by previous Xcode toolchains, but the latest toolchain gives an error. I could not find a relevant issue in wxsqlite3 repository.

**Comment by georgeef** [comment]
@guanlisheng as FYI

**Comment by guanlisheng** [comment]
Thanks, I still use xcode v16.2

**Comment by guanlisheng** [comment]
@georgeef , can you try out wxWidgets v3.2.8? https://wxwidgets.org/news/2025/04/wxwidgets-3.2.8-released/

**Comment by guanlisheng** [comment]
> Fix third party libraries build with Xcode 16.3.

**Comment by georgeef** [comment]
It looks good.

**Comment by guanlisheng** [comment]
Great.  
Seems we need to upgrade wxWidgets again after 
- #7400 

Would you mind taking a look?

**Comment by georgeef** [comment]
I compiled and tested MMEX with wxWidgets 3.2.8 on macOS. It looks good.

The second problem in the description still remains. I think both `-msse4.2` and `-maes` are x86 specific, so the first term `(NOT LINUX)` in the if expression should be removed. But maybe I'm wrong.

**Comment by georgeef** [comment]
The second problem is fixed in #7478.

**Comment by whalley** [comment]
```
if((NOT LINUX) OR (NOT ";aarch64;arm;arm64;armv8b;armv8l;" MATCHES ";${CMAKE_HOST_SYSTEM_PROCESSOR};"))
    set (CMAKE_C_FLAGS "-msse4.2 -maes")
endif()
```
@georgeef My normal build on on my M1 Mac targets both x86 and arm64 with `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`

The build fails, presumably as the CMAKE_C_FLAGS get set based on my host arm64 system.

I'm not sure how to vary the CMAKE_C_FLAGS per target. Any clues?

**Comment by georgeef** [comment]
No idea. Which Xcode version do you use?

All tests below are on M3 with Xcode 16.3, after compiling wxWidgets 3.2.8 with `--enable-universal-binary=arm64,x86_64`.

- `CMAKE_OSX_ARCHITECTURES` undefined (implies arm64), `CMAKE_C_FLAGS` without `-msse4.2 -maes`
no error

- `CMAKE_OSX_ARCHITECTURES` undefined (implies arm64), `CMAKE_C_FLAGS` with `-msse4.2 -maes`
Compilation error:
> clang: error: unsupported option '-maes' for target 'arm64-apple-darwin24.4.0'

- `CMAKE_OSX_ARCHITECTURES="arm64;x86_64"`, `CMAKE_C_FLAGS` with `-msse4.2 -maes`
Linker errors:
> Undefined symbols for architecture x86_64:
> ... (`_luaL_*`, `_lua_*`, `_pcre2_*`)
> ld: symbol(s) not found for architecture x86_64

- `CMAKE_OSX_ARCHITECTURES="arm64;x86_64"`, `CMAKE_C_FLAGS` without `-msse4.2 -maes`
Compilation errors:
> error: '__builtin_ia32_aeskeygenassist128' needs target feature aes
> error: always_inline function '_mm_aesimc_si128' requires target feature 'aes', but would be inlined into function 'aesGenKeyDecrypt' that is compiled without support for 'aes'

I cannot build for universal binary (I never tried before).

@whalley, @guanlisheng 
How do you compile for universal binary. Do you have `lua` and `pcre2` pre-installed? I have them pre-installed with brew, probably they are arm64-only.

**Comment by whalley** [comment]
For now, until we resolve this I have reverted to using Xcode 16.2 and reverted the `3rd/CMakeLists.txt` change. This allows the Universal binary to be built.

**Comment by georgeef** [comment]
The original condition
```
if((NOT LINUX) OR (NOT ";aarch64;arm;arm64;armv8b;armv8l;" MATCHES ";${CMAKE_HOST_SYSTEM_PROCESSOR};"))
    set (CMAKE_C_FLAGS "-msse4.2 -maes")
endif()
```

needs some improvement to cover all cases, but it would become too complicated if we try to make it more precise. Currently it works for a universal build because it evaluates to true on macOS, independently of other settings.

Maybe a more flexible solution is to skip the setting of `CMAKE_C_FLAGS` for macOS, and to pass the flags from the command line if needed, like
> cmake -DCMAKE_CXX_FLAGS="-w -std=c++20" -DCMAKE_C_FLAGS="-msse4.2 -maes" ...

The opposite would be to set `CMAKE_C_FLAGS` to `-msse4.2 -maes` for macOS by default (as in the original condition), and to overwrite it to empty when it is not needed. But I cannot find an easy way to overwrite from command arguments.

Also it makes more sense to have a positive rather than a negative condition, like
```
(";x86;x86_64;" MATCHES ";${CMAKE_HOST_SYSTEM_PROCESSOR};")
```

**Comment by whalley** [comment]
https://stackoverflow.com/questions/67490441/cmake-universal-binary-arch-depending-compile-options. ?

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/7437#issuecomment-2856256153 works fine for me (with this adjustment - https://github.com/moneymanagerex/moneymanagerex/issues/7437#issuecomment-2857731805).

WxWidgets built similarly with 
`export MAKEFLAGS=-j8 ; export MACOSX_DEPLOYMENT_TARGET=10.12 ; ../configure --disable-debug --disable-shared --with-cxx=20 --enable-stl --with-macosx-version-min=10.12 --enable-universal-binary=arm64,x86_64
make`
